### ISSUE TITLE
Error ao conectar com o firebird 2.1

### ISSUE THREAD

**Issue by ramyres110** [plasoft-software/plasoft-firebird#1]
**Estou tentando conectar em um banco de dados firebird:**

![image](https://user-images.githubusercontent.com/17148824/62297926-6b28ed00-b448-11e9-8f95-8f54cafb3aed.png)

**Com o código:**
```js
const path = require('path');
const Firebird = require('plasoft-firebird');
const options = {
    host: '127.0.0.1',
    port: 3050,
    database: path.normalize('C:\\Database\\Database7.FDB'),
    user: 'SYSDBA',
    password: 'masterkey',
};
Firebird.attach(options, (err, db) => {
    if (err) throw err;
    console.log('Connected!');
    db.detach();
});
```

**Está me retornando esse Erro: **
```bash
fs.js:136
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:136:11)
    at Object.close (fs.js:394:20)
    at C:\Users\ramyr\Desenvolvimento\_Nodejs\try-npm-plasoft-firebird\node_modules\plasoft-firebird\lib\messages.js:148:28
    at search (C:\Users\ramyr\Desenvolvimento\_Nodejs\try-npm-plasoft-firebird\node_modules\plasoft-firebird\lib\messages.js:115:13)
    at C:\Users\ramyr\Desenvolvimento\_Nodejs\try-npm-plasoft-firebird\node_modules\plasoft-firebird\lib\messages.js:54:21
    at FSReqWrap.wrapper [as oncomplete] (fs.js:467:17)
```

**Alterei o arquivo .\lib\messages.js:**
```
line:148    fs.close(handle, () => { });
```

**E respondeu com o Error:**
```bash
Error: unsupported on-disk structure for file C:\Database\Database7.FDB; found 32779.15, support @4.@5
    at doCallback (C:\Users\ramyr\Desenvolvimento\_Nodejs\try-npm-plasoft-firebird\node_modules\plasoft-firebird\lib\index.js:1250:18)
    at C:\Users\ramyr\Desenvolvimento\_Nodejs\try-npm-plasoft-firebird\node_modules\plasoft-firebird\lib\index.js:2947:21
    at C:\Users\ramyr\Desenvolvimento\_Nodejs\try-npm-plasoft-firebird\node_modules\plasoft-firebird\lib\messages.js:149:25
    at search (C:\Users\ramyr\Desenvolvimento\_Nodejs\try-npm-plasoft-firebird\node_modules\plasoft-firebird\lib\messages.js:115:13)  
    at C:\Users\ramyr\Desenvolvimento\_Nodejs\try-npm-plasoft-firebird\node_modules\plasoft-firebird\lib\messages.js:54:21
    at FSReqWrap.wrapper [as oncomplete] (fs.js:467:17)
```
**Que é o mesmo erro encontrado no node-firebird!**

Estou reportando para que caso o erro seja meu, o que posso alterar??

**Obs:** Tive de realizar a instalação manual do `windows-1252`

Grato, Att: Ramyres Aquino.

**Comment by ramyres110** [comment]
Mais uma coisa, minha versão do Node é a v10.16.0.

**Comment by furflez** [comment]
Bom dia, estamos fazendo alguns testes aqui, mas esse erro só aconteceu quando o firebird não foi instalado como serviço.
Quando foi instalado como um serviço mesmo com o node 10 funcionou tranquilo.

**Comment by ramyres110** [comment]
Já está instalado...

![image](https://user-images.githubusercontent.com/17148824/62370638-14371c80-b509-11e9-8518-b2b357bc28a6.png)

Eu o utilizo em outras aplicações em Delphi e C++, apenas no Node que não está Ok... 

Se tiver alguma configuração extra, tanto no Node quanto no Firebird estou disposto a fazer, o que não posso é atualizar a versão.

**Comment by ramyres110** [comment]
Voltei para o node-firebird e o que não estava funcionando era a questão da porta... utilizamos varias portas diferentes. Logo, se alguém tiver problema confiram as portas e as configurações das mesmas!
